# Generated by Django 2.2 on 2019-04-25 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_stduents'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='stduents',
            new_name='students',
        ),
    ]
